#!/bin/bash
# test-pimp: test pimp tool (run with: $ bash test-pimp)
# Copyright (c) 2024 Bluenetics GmbH
# SPDX-License-Identifier: Apache-2.0

   PIMP=pimp
   TEST="bash test-pimp"

#===============================================================================
# test-install --claim ...   # claim something
#===============================================================================

   if [ "$1" == "--claim" ]; then
      shift
      printf "\x1b[36m"  # cyan
      echo "claim: $*"
      printf "\x1b[0m"
      exit 0
   fi

#===============================================================================
# test-install <cmd>      # run command and print result
# test-install -e <cmd>   # check error when run command and print result
#===============================================================================

   if [ "$*" != "" ]; then
      if [ "$1" == '-f' ]; then
         GOOD="1"
         shift
      else
         GOOD="0"
      fi

      CMD=$*
      #ec -g "CMD=$CMD"

      $CMD 2>/dev/null >/dev/null && ERR=0 || ERR=1
      #$CMD && ERR=0 || ERR=1

      if [ "$ERR" == "$GOOD" ]; then
         echo "$CMD" >>deps/tests
         echo "  OK: $CMD"
      else
         echo "  *** $CMD" >>deps/errors
         printf "\x1b[31m"  # red
         echo "  FAIL: $CMD"
         printf "\x1b[0m"
         exit 1
      fi
      exit 0
   fi

#===============================================================================
# setup fixture
#===============================================================================

   if [ "$*" == "" ]; then
		   rm -rf deps
		   mkdir deps
		   touch deps/tests
		   touch deps/errors

		   mkdir deps/bin

		   bash $PIMP ---y "PIMP=$PIMP"
		   chmod +x $PIMP

       export PATH=`pwd`/../bin:$PATH
   fi

#===============================================================================
$TEST --claim available deps/bin folder
#===============================================================================

   $TEST ls deps/bin

#===============================================================================
$TEST --claim help is working
#===============================================================================

   $TEST $PIMP -?
   $TEST $PIMP --?
   $TEST $PIMP --help

#===============================================================================
$TEST --claim version is supported
#===============================================================================

   $TEST $PIMP --version
   $TEST $PIMP --v

#===============================================================================
$TEST --claim --path option working
#===============================================================================

   $TEST $PIMP --path .git
   $TEST $PIMP --path .pimp

#===============================================================================
$TEST --claim fail in case of missing arguments for --install
#===============================================================================

   $TEST -f bash $PIMP --install
   $TEST -f bash $PIMP --install pimp
   echo '  => unset BIN'; unset BIN
   $TEST -f bash $PIMP --install $PIMP
   echo '  => export BIN=junk/bin';  export BIN=junk/bin
   $TEST -f bash $PIMP --install $PIMP
   echo '  => export BIN=deps/bin';  export BIN=deps/bin
   $TEST bash $PIMP --install ../bin/$PIMP
   $TEST ls deps/bin/pimp  # is pimp installed in deps/bin
   $TEST rm -f deps/bin/pimp  # remove pimp in deps/bin

   $TEST bash $PIMP --install ../bin/$PIMP deps/bin
   $TEST ls deps/bin/pimp  # is pimp installed in deps/bin

   $TEST rm -f deps/bin/pimp  # remove pimp in deps/bin
   $TEST bash $PIMP --install

#===============================================================================
# print summary
#===============================================================================

   printf "\x1b[36m"  # cyan
   echo "summary: `cat deps/tests | wc -l` tests, `cat deps/errors | wc -l` error(s)"
   printf "\x1b[0m"

   printf "\x1b[31m"  # red
   cat deps/errors
   printf "\x1b[0m"
   exit 0
